version: 0.2
env:
  variables:
    AWS_REGION: "ap-south-1"

phases:
  pre_build:
    commands:
      # Log into ECR
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 145023127397.dkr.ecr.ap-south-1.amazonaws.com
      # Get the ECR repository URL
      - REPOSITORY_URI=145023127397.dkr.ecr.ap-south-1.amazonaws.com/ecs-angular-14
      # Get the image tag from Git commit ID
      - IMAGE_TAG=proj-frontend-$CODEBUILD_BUILD_NUMBER
      
  build:
    commands:
      # Build Docker image
      - echo Building the Docker image...
      - pwd
      - ls
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
      # Push the Docker image to ECR
      - echo Pushing the Docker image to ECR...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
      
  post_build:
    commands:
      # Write image details to a file
      - echo Build completed on `date`
      - echo pushing to repo
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      
      # Writing to imagedefination.json: 
      - aws ecs describe-task-definition --task-definition angular-14-ecs --region ap-south-1 | jq .taskDefinition > taskdef.json
      - DOCKER_CONTAINER_NAME=ecs-frontend
      - printf '[{"name":"%s","imageUri":"%s"}]' $DOCKER_CONTAINER_NAME $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - echo $DOCKER_CONTAINER_NAME
      - echo printing imagedefinitions.json
      - cat taskdef.json
      - cat appspec.yml
        

artifacts:
  files:
    - taskdef.json
    - appspec.yml
    - imagedefinitions.json
